[package]
name = "canzero-codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
canzero-config = { git = "https://github.com/mu-zero-HYPERLOOP/canzero-config.git" }
